# Generated by Django 5.0.1 on 2024-04-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognews',
            name='description_company',
            field=models.TextField(default='Описание для нижнего блока', verbose_name='Description_company'),
        ),
        migrations.AddField(
            model_name='blognews',
            name='logo_photo',
            field=models.ImageField(blank=True, null=True, upload_to='news_photos/', verbose_name='Logo Photo'),
        ),
        migrations.AlterField(
            model_name='blognews',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blognews',
            name='description_small',
            field=models.TextField(default='', max_length=500, verbose_name='Description_small'),
        ),
    ]
