# Generated by Django 5.0.1 on 2024-02-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description_two',
            field=models.TextField(default='Описание', verbose_name='description_two'),
        ),
    ]
