# Generated by Django 5.0.1 on 2024-02-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_shop_inverter_client_visit_shop_inverter_image_two_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_inverter',
            name='description_three',
            field=models.TextField(default='Полное Описание', verbose_name='description_three'),
        ),
    ]
