# Generated by Django 5.0.1 on 2024-02-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_shop_inverter_description_three'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_inverter',
            name='image_three',
            field=models.ImageField(default='default_image_three.jpg', upload_to='services', verbose_name='photo_three'),
        ),
    ]
