# Generated by Django 5.0.1 on 2024-02-17 15:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_shop_inverter_image_three'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=20)),
                ('message', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shop_inverter',
            name='client_visit',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='shop_inverter',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='shop_inverter',
            name='description_three',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='shop_inverter',
            name='description_two',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
