# Generated by Django 5.0.1 on 2024-02-22 08:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_shop_encoders_client_visit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_Indastrial_Electroniks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_two', models.CharField(default='Второй Заголовок', max_length=100, verbose_name='name_two')),
                ('description', ckeditor.fields.RichTextField()),
                ('description_two', ckeditor.fields.RichTextField()),
                ('description_three', ckeditor.fields.RichTextField(default='Описание', verbose_name='description three')),
                ('client_visit', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='services', verbose_name='photo')),
                ('image_two', models.ImageField(default='default_image.jpg', upload_to='services', verbose_name='photo_two')),
                ('image_three', models.ImageField(default='default_image_three.jpg', upload_to='services', verbose_name='photo_three')),
                ('is_main', models.BooleanField(default=False)),
                ('link', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Indastrial-Electroniks',
                'verbose_name_plural': 'Indastrial-Electroniks',
            },
        ),
    ]
