# Generated by Django 5.0.1 on 2024-02-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_shop_indastrial_electroniks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='ServicesMain',
        ),
        migrations.AlterModelOptions(
            name='servicesmain',
            options={'verbose_name': 'Services MAIN', 'verbose_name_plural': 'Services MAIN'},
        ),
    ]
