# Generated by Django 5.0.1 on 2024-02-22 14:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_rename_services_servicesmain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_board',
            name='client_visit',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop_board',
            name='description_three',
            field=ckeditor.fields.RichTextField(default='Описание', verbose_name='description three'),
        ),
        migrations.AddField(
            model_name='shop_board',
            name='image_three',
            field=models.ImageField(default='default_image_three.jpg', upload_to='services', verbose_name='photo_three'),
        ),
        migrations.AddField(
            model_name='shop_board',
            name='image_two',
            field=models.ImageField(default='default_image.jpg', upload_to='services', verbose_name='photo_two'),
        ),
        migrations.AddField(
            model_name='shop_board',
            name='name_two',
            field=models.CharField(default='Второй Заголовок', max_length=100, verbose_name='name_two'),
        ),
        migrations.AlterField(
            model_name='shop_board',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='shop_board',
            name='description_two',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
