# Generated by Django 5.0.1 on 2024-02-28 19:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_shop_repair_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='process_photos/')),
                ('description', ckeditor.fields.RichTextField(default='Описание', verbose_name='description')),
            ],
            options={
                'verbose_name': 'Our Process',
                'verbose_name_plural': 'Our Process',
            },
        ),
    ]
