# Generated by Django 5.0.1 on 2024-02-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='steps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Steps'),
        ),
    ]
