# Generated by Django 5.0.1 on 2024-02-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_process_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='steps',
            field=models.IntegerField(default=0, verbose_name='Steps'),
        ),
    ]
