# Generated by Django 5.0.1 on 2024-03-20 10:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_blockcpcfour_errors_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockcpcfour',
            name='description_four',
            field=ckeditor.fields.RichTextField(default='Описание', verbose_name='description four'),
        ),
    ]
