# Generated by Django 5.0.1 on 2024-03-21 09:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_blockcpcfour_description_four'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockcpcfour',
            name='description_seven',
            field=ckeditor.fields.RichTextField(default='Описание', verbose_name='description seven'),
        ),
        migrations.AddField(
            model_name='blockcpcfour',
            name='description_six',
            field=ckeditor.fields.RichTextField(default='Описание', verbose_name='description six'),
        ),
    ]
