# Generated by Django 5.0.1 on 2024-04-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_officecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockcpcfour',
            name='name_three',
            field=models.CharField(default='Третий Заголовок', max_length=100, verbose_name='name_three'),
        ),
    ]
