# Generated by Django 5.0.1 on 2024-04-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_officecontact_city_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officecontact',
            name='lunch',
            field=models.CharField(default='обед', max_length=100),
        ),
    ]
