# Generated by Django 5.0.1 on 2024-05-18 17:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_officecontact_lunch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='facts_photos/')),
                ('description', ckeditor.fields.RichTextField(default='Описание', verbose_name='description')),
                ('icon_facts', models.ImageField(blank=True, null=True, upload_to='facts_icons/', verbose_name='Icon Facts')),
            ],
            options={
                'verbose_name': 'Наши преимущества',
                'verbose_name_plural': 'Наши преимущества',
            },
        ),
    ]
