# Generated by Django 5.0.1 on 2024-05-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_facts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='icon_facts',
            field=models.ImageField(default='fa fa-icon', upload_to='facts_icons/', verbose_name='Icon Facts'),
        ),
    ]
