# Generated by Django 5.0.1 on 2024-05-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_alter_facts_icon_facts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='icon_facts',
            field=models.CharField(default='flaticon-star', max_length=100, verbose_name='Icon Class'),
        ),
    ]
