# Generated by Django 5.0.1 on 2024-05-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_alter_facts_icon_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmain',
            name='h1_description',
            field=models.TextField(default='Описание', max_length=100, verbose_name='h1_description'),
        ),
        migrations.AddField(
            model_name='servicesmain',
            name='h1_name',
            field=models.CharField(default='Имя', max_length=100, verbose_name='h1_name'),
        ),
        migrations.AlterField(
            model_name='servicesmain',
            name='description',
            field=models.TextField(default='Описание', verbose_name='description'),
        ),
    ]
