# Generated by Django 5.0.1 on 2024-05-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_servicesmain_h1_description_servicesmain_h1_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmain',
            name='h1_description',
            field=models.TextField(default='Описание', max_length=150, verbose_name='h1_description'),
        ),
    ]
