# Generated by Django 5.0.1 on 2024-05-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_rename_link_servicesmain_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_indastrial_electroniks',
            name='h1_description',
            field=models.TextField(default='Описание', max_length=150, verbose_name='h1_description'),
        ),
        migrations.AddField(
            model_name='shop_indastrial_electroniks',
            name='h1_name',
            field=models.CharField(default='Имя', max_length=100, verbose_name='h1_name'),
        ),
    ]
