# Generated by Django 5.0.1 on 2024-05-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_shop_indastrial_electroniks_h1_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_indastrial_electroniks',
            name='h1_description',
            field=models.TextField(default='Описание', max_length=200, verbose_name='h1_description'),
        ),
    ]
