# Generated by Django 5.0.1 on 2024-05-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_alter_shop_indastrial_electroniks_h1_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_indastrial_electroniks',
            old_name='h1_description',
            new_name='h1_description_ind',
        ),
        migrations.RenameField(
            model_name='shop_indastrial_electroniks',
            old_name='h1_name',
            new_name='h1_name_ind',
        ),
    ]
